---
networks:
  mynet2:

volumes:
  myvol2:

services:
  myapp2:
     image: stackupiss/northwind-app:v1
     environment:
       - APP_PORT=3000
       - DB_HOST=mydb2
       - DB_USER=root
       - DB_PASSWORD=changeit
     ports:
       - 8081:3000
     networks:
       - mynet2
  mydb2:
     image: stackupiss/northwind-db:v1 
     volumes:
       - myvol2:/var/lib/mysql
     networks:
        - mynet2

...
