# BGGDB
---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns
  labels:
    name: bggns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  labels:
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-pod
  template:
    metadata:
      name: bggdb-pod
      labels:
        name: bggdb-pod
        dept: eng
        purpose: database
      namespace: bggns
    spec:
      volumes:
        - name: bggdb-vol
          persistentVolumeClaim:
            claimName: data-pvc
      containers:
        - name: bggdb-pod
          image: stackupiss/bgg-database:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: bggdb-vol
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3306
      targetPort: 3306
  selector:
    name: bggdb-pod
...
#
# BGGAPP#
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  labels:
    name: bggapp-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
        dept: eng
        purpose: application
      namespace: bggns
    spec:
      containers:
        - name: bggapp-pod
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: BGG_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: bggapp-cm
                  key: BGG_DB_USER
            - name: BGG_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bggapp-cm
                  key: BGG_DB_HOST
            - name: BGG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bggapp-secret
                  key: BGG_DB_PASSWORD
          ports:
            - name: app-port
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: app-port
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: app-port
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: app-port
  selector:
    name: bggapp-pod
---
