---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  labels:
    name: dov-cm
data:
  INSTANCE_NAME: dov-cm-bearzzz
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      abc: abc
  template:
    metadata:
      name: dov-pod
      labels:
        name: dov-pod
        dept: eng
        abc: abc
      namespace: myns
    spec:
      containers:
        - name: dov-container
          image: stackupiss/dov-bear:v2
          imagePullPolicy: IfNotPresent
          env:
          - name: INSTANCE_NAME
            valueFrom:
              configMapKeyRef:
               name: dov-cm
               key: INSTANCE_NAME
          - name: INSTANCE_HASH
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 3000
...
---
apiVersion: v1
kind: Service
metadata:
  name: dov-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 3000
  selector:
    name: dov-pod
...