---
apiVersion: v1
kind: Secret
metadata:
  name: mydb-secret
# type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mydb-cluster
  labels:
    name: mydb-cluster
spec:
  replicas: 2
  secretName: mydb-secret
  # mysqlVersion: "8.0"
  volumeSpec:
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: do-block-storage
---
