---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wp-netpol-deny-all
  labels:
    name: wp-netpol-deny-all
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wp-netpol-allow-fe
  labels:
    name: wp-netpol-allow-fe
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: wpapp-pod
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wp-netpol-allow-api
  labels:
    name: wp-netpol-allow-api
spec:
  podSelector:
    matchLabels:
      name: wpapp-pod
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          type: wpapp-svc
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: database