# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: wp-netpol-deny-all-app
#   labels:
#     name: wp-netpol-deny-all-app
# spec:
#   podSelector:
#     matchLabels:
#       name: wpapp-pod
#   policyTypes:
#     - Ingress
#     - Egress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: wp-netpol-deny-all-db
#   labels:
#     name: wp-netpol-deny-all-db
# spec:
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/component: database
#   policyTypes:
#     - Ingress
#     - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wp-netpol-allow-db
  labels:
    name: wp-netpol-allow-db
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: wpapp-pod
  egress:
  - to:
    - podSelector:
        matchLabels:
           name: wpapp-pod
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wp-netpol-allow-apo
  labels:
    name: wp-netpol-allow-app
spec:
  podSelector:
    matchLabels:
      name: wpapp-pod
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
  egress:
    - to:
      - podSelector:
            matchLabels:
              role: master
